### ISSUE TITLE
HostingServices' does not contain a definition for 'GetDefaultService

### ISSUE THREAD

**Issue by fabbbiob** [aspnet/BugTracker#48]
just downloaded and executed 

:(  Oops.
500 Internal Server Error
Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException
C:\Users\fabio\Source\Repos\BugTracker-master\src\BugTracker\Program.cs(30,51): error CS0117: 'HostingServices' does not contain a definition for 'GetDefaultServices'
C:\Users\fabio\Source\Repos\BugTracker-master\src\BugTracker\Program.cs(31,91): error CS0200: Property or indexer 'HostingEnvironment.WebRoot' cannot be assigned to -- it is read only
C:\Users\fabio\Source\Repos\BugTracker-master\src\BugTracker\Program.cs(31,68): error CS7036: There is no argument given that corresponds to the required formal parameter 'appEnvironment' of 'HostingEnvironment.HostingEnvironment(IApplicationEnvironment, IEnumerable<IConfigureHostingEnvironment>)'
C:\Users\fabio\Source\Repos\BugTracker-master\src\BugTracker\Program.c

**Comment by jchadwick** [comment]
Yup, me too - trying to run on OS X w/ Mono.  KVM beta2

**Comment by sriramgd** [comment]
I was able to get the program running on Ubuntu with Mono, KVM beta2, but doing the following. If it helps, I can submit a pull request.

diff --git a/src/BugTracker/Program.cs b/src/BugTracker/Program.cs
index 3487b34..3166d4b 100644
--- a/src/BugTracker/Program.cs
+++ b/src/BugTracker/Program.cs
@@ -27,9 +27,8 @@ namespace BugTracker
             config.AddCommandLine(args);
             
             var serviceCollection = new ServiceCollection();
-            serviceCollection.Add(HostingServices.GetDefaultServices(config));
-            serviceCollection.AddInstance<IHostingEnvironment>(new HostingEnvironment() { WebRoot = "wwwroot" });
-            var services = serviceCollection.BuildServiceProvider(_hostServiceProvider);
+            serviceCollection.Add(HostingServices.Create(_hostServiceProvider));
+            var services = serviceCollection.BuildServiceProvider();
 
             var context = new HostingContext()
             {
@@ -54,4 +53,4 @@ namespace BugTracker
             return Task.FromResult(0);
         }
     }
-}
\ No newline at end of file
+}

**Comment by sriramgd** [comment]
I created a pull request: https://github.com/aspnet/BugTracker/pull/49

**Comment by c0ntinuum** [comment]
+1 what do we need to do to get this merged? :)

**Comment by sriramgd** [comment]
@c0ntinuum, looks like the KVM are updated on a regular basis. Moreover I am not sure this demo is actively maintained. Given this, my workaround may or may not be valid now. If you want to try it out, you can just apply the patch I have pasted.

**Comment by c0ntinuum** [comment]
@sriramgd I already applied your patch and it fixes the issue.

What I'm suggesting is the maintainer merge the PR ;)

**Comment by arserbin3** [comment]
sriramgd's patch also works for me on Windows with VS 2015 CTP6
